AT-251 feat: реализовать работу через discriminator типа
dex-it/dex-common pull request #140
Opened 2023-12-20 08:07 UTC by vikword

2023-12-21 10:19 UTC, mmx003 requested changes

2024-03-24 17:35 UTC, juk-777 commented on src/Dex.Cap/Dex.Cap.Outbox/BaseOutboxTypeDiscriminator.cs
> +        return Discriminator.TryGetKey(type, out discriminator);
Такое ощущение, что кажется лучше изменить сигнатуру метода и делать просто GetDiscriminator и возвращать string а не bool. Внутри метода выбрасывать исключение DiscriminatorResolveTypeException. Продолжение ведь в любом случае невозможно елси тут не будет получено значение - так зачем тогда выносить обработку наверх елси можно прямо тут упасть.

2024-03-24 17:35 UTC, juk-777 commented on src/Dex.Cap/Dex.Cap.Outbox/BaseOutboxTypeDiscriminator.cs
> +        return Discriminator.TryGetValue(discriminator, out type);
тут аналогично

2024-03-24 17:39 UTC, juk-777 commented on src/Dex.Cap/Tests/Dex.Cap.Ef.Tests/BaseTest.cs
> +            Add(nameof(EmptyOutboxMessage), typeof(EmptyOutboxMessage).AssemblyQualifiedName!);
EmptyOutboxMessage думаю нужно добавлять сразу в базовом классе, он ведь нужен всегда. Я как пользователь могу не знать что нужно его добавить в свою реализацию.

2024-04-01 17:37 UTC, juk-777 approved these changes

2024-04-01 19:00 UTC, juk-777 approved these changes

2024-04-01 19:01 UTC, juk-777 approved these changes

2024-04-02 05:53 UTC, sfetesko approved these changes

2024-04-27 04:52 UTC, mmx003 approved these changes

2024-04-27 04:52 UTC, merged