NewCollectionReversibleDictionary feat: добавить реверсивный словарь …
dex-it/dex-common pull request #141
Opened 2023-12-21 13:22 UTC by vikword

…и обновить версию до 1.0.26

2023-12-22 09:44 UTC, mmx003 requested changes

2023-12-22 09:44 UTC, mmx003 commented on src/Dex.Types/ReversibleDictionary.cs
> +                _forwardDictionary.Add(key, value);
тут единственно мне не нравится
если будет ошибка в _reverseDictionary.Add(value, key);
то из первого словаря должно быть удалено

2023-12-22 10:12 UTC, mmx003 commented on src/Dex.Types/ReversibleDictionary.cs
> +                _forwardDictionary.Add(key, value);
был не прав, вверху проверка есть

2023-12-22 14:07 UTC, mmx003 commented
посмотрите на сколько трудно реализовать полный интерфейс IDictionary

2023-12-27 07:18 UTC, mmx003 requested changes

2023-12-27 07:18 UTC, mmx003 commented on src/Dex.Types/ReversibleDictionary.cs
> +                if (ContainsKey(key))
зачем тут проверять, если индексатор это и сам делает ?

2023-12-27 07:18 UTC, mmx003 commented on src/Dex.Types/ReversibleDictionary.cs
> +                if (ContainsKey(key))
и мне кажется что словарики д.б. одинаковой длинны, а у тебя сейчас это так не будет

напиши плиз тест

добавляем пары

1, А
2, А

у тебя будет
прямой словарь 

1, А
2, А

а обратный 

А, 2

длины не равны!

2023-12-27 07:32 UTC, vikword commented on src/Dex.Types/ReversibleDictionary.cs
> +                if (ContainsKey(key))
так не получится создать словарь с двумя одинаковыми значениями или ключами 
по типу:
1, А
2, А

2023-12-27 07:42 UTC, vikword commented on src/Dex.Types/ReversibleDictionary.cs
> +                if (ContainsKey(key))
if (ContainsKey(key)) проверка нужна для того чтоб если нет такого ключа чтоб создалась новая пара

2023-12-28 20:01 UTC, merged