Метрики для прометеуса по кол-ву необработанных сообщений
dex-it/dex-common pull request #55
Opened 2022-02-14 08:13 UTC by sfetesko

Метрики реализованы с помощью https://www.app-metrics.io
Обновление значения метрики происходит в основном цикле обработки

2022-02-14 08:39 UTC, mmx003 commented
не должена запись метрики, тем более в Prometeus происходить в Outbox.Ef
Архитектура должна быть примерно такой
Outbox оперирует абстракцией IMetricsProvider (подставляется конкретная реализация Prometeus, Kibana и т.д.)
IMetricsProvider реализуется в отдельной либе (Prometeus, Kibana) для каждого типа своя, расширение которое добавляет его в контейнер тоже свое.
Outbox в случае если IMetricsProvider не задан не пишет метрику соттветственно

2022-02-14 08:40 UTC, mmx003 requested changes
написал в комент

2022-02-16 08:40 UTC, sfetesko commented
> не должена запись метрики, тем более в Prometeus происходить в Outbox.Ef Архитектура должна быть примерно такой Outbox оперирует абстракцией IMetricsProvider (подставляется конкретная реализация Prometeus, Kibana и т.д.) IMetricsProvider реализуется в отдельной либе (Prometeus, Kibana) для каждого типа своя, расширение которое добавляет его в контейнер тоже свое. Outbox в случае если IMetricsProvider не задан не пишет метрику соттветственно

IMetrics который проброшен в Outbox.Ef это уже и есть фактически IMetricsProvider. В нем нет реализации записи в Prometeus. Как я вижу в нем идея как с абстаркцией ILogger, и куда и как должна реально отдавать метрики эта абстракция определяется в приложении, а не в библиотеке.
В тестовом приложении Dex.Cap.AspNet.Test это прописывается в Program.Main

2022-09-20 23:06 UTC, closed without merging

2022-09-20 23:07 UTC, mmx003 commented
доработаю